### ISSUE TITLE
Latest versions of libraries

### ISSUE THREAD

**Issue by ulaserdegor** [muratcanbur/ProjectX#29]
You keep library versions in another class. This is the recommended usage, but how do you check for updates? Android Studio warns the versions kept in the Gradle file.

For example, your cottal version is 1.3.41 and the current one is 1.3.72.

**Comment by muratcanbur** [comment]
There is a plugin for this problem. 

https://github.com/ben-manes/gradle-versions-plugin

This plugin provides a task to determine which dependencies have updates.
